;"use strict";
(function packageJson2properties() {
  let data = JSON.parse(document.body.firstElementChild.textContent);
  let prefs = data.preferences;
  // let win = window.open('', '', 'width=420,height=230,resizable,scrollbars=yes,status=1');
  // let win = window.open("", "preferences from package.json", "resizable=1,width=400,height=400");
  // let doc = win.document;
  // doc.title = "preferences from package.json";
  let text = '#\n# Generated by ' + (new Error()).stack.split(/\n/)[0] + '\n# Add to en-US.properties as is,\n# adjust content for other locales.\n#\n';
  ['description', 'homepage', 'name', 'title'].forEach(function(field) {
    console.log(data[field]);
    text += 'addon_' + field + '=' + data[field].replace(/\n/g, '\\\n').replace(/\\"/g, '"') + '\n';
  });
  prefs.forEach(function(pref) {
    text += pref.name + '_description=' + pref.description.replace(/\n/g, '\\\n').replace(/\\"/g, '"') + '\n';
    text += pref.name + '_title=' + pref.title.replace(/\n/g, '\\\n').replace(/\\"/g, '"') + '\n';
  });
  let blob = new Blob([text], {
    'type': 'text/plain;charset=utf8'
  });
  let div = document.body.appendChild(document.createElement('div'));
  let a = div.appendChild(document.createElement('a'));
  div.style = 'position:fixed;top:50%;left:50%';
  a.href = URL.createObjectURL(blob);
  let filename = 'en-US.properties-frag' + Date.now() + '.txt';
  a.textContent = 'download ' + filename;
  a.title = '... or drag me to a new browser tab';
  a.download = filename;
  let close = div.appendChild(document.createElement('a'), a);
  close.style = 'text-decoration:none;padding:1em';
  close.href = 'Close';
  close.innerHTML = '&times;';
  close.addEventListener('click', function(event) {
    event.preventDefault();
    document.body.removeChild(event.target.parentElement);
  });
})();